steps:
  - label: ":julia: [CUDA] Run tests on Julia v{{matrix.version}}"
    matrix:
      setup:
        version:
          - "1"
          - "1.10"
    env:
      GROUP: CUDA
    plugins:
      - JuliaCI/julia#v1:
          version: "{{matrix.version}}"
    commands:
      - |
        julia --project=test -e '
          import Pkg
          Pkg.add(; name = "CUDA")'
        rm test/Manifest.toml
        julia --project -e'
          import Pkg
          println("+++ :julia: Running tests")
          Pkg.test(; coverage=false)'
    agents:
      queue: "juliagpu"
      cuda: "*"
    timeout_in_minutes: 120
    # Don't run Buildkite if the commit message includes the text [skip tests]
    if: build.message !~ /\[skip tests\]/
