name: Documentation

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:

jobs:
  build:
    name: "Documentation"
    uses: "SciML/.github/.github/workflows/documentation.yml@v1"
    secrets: "inherit"
